FROM python:3.10-slim
RUN apt-get update
RUN apt-get install -y net-tools telnet iputils-ping

RUN apt-get install -y gcc default-libmysqlclient-dev

ENV PYTHONPATH="/usr/local/lib"

COPY src/task_queue/ /usr/local/lib/task_queue/
COPY src/utils/ /usr/local/lib/utils/
COPY src/my_project/ /usr/local/lib/my_project/

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY start-worker.sh .
CMD ./start-worker.sh; sleep infinity
