FROM python:3.10-slim
RUN apt-get update
RUN apt-get install -y net-tools telnet iputils-ping

# RUN apt-get install -y rabbitmq-server
RUN apt-get install -y gcc default-libmysqlclient-dev

# Dev environment
RUN apt-get install -y git-all

ENV PYTHONPATH=./src

# Persist bash history
RUN SNIPPET="export PROMPT_COMMAND='history -a' && export HISTFILE=/commandhistory/.bash_history" \
    && echo "$SNIPPET" >> "/root/.bashrc"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
